name: Create a Release & Publish to GPR

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'lib/VERSION'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: SecZetta/sz_gha_scripts
          token: ${{ secrets.REPO_AND_PACKAGE_TOKEN }}
          path: .github/actions/
      - name: Build and Release
        uses: ./.github/actions/build_and_release_gem
        with:
          github_token: ${{ secrets.REPO_AND_PACKAGE_TOKEN }}
      - name: Publish to GPR
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
          OWNER: ${{ github.repository_owner }}
